Use reusable workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -8,55 +8,22 @@ on:
       - main
   pull_request:
 
-env:
-  CARGO_TERM_COLOR: always
-
 jobs:
-  publish:
-    name: Publishing for ${{ matrix.job.target }}
-    runs-on: ${{ matrix.job.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        rust: [stable]
-        job:
-          - os: ubuntu-latest
-            target: x86_64-unknown-linux-gnu
-          - os: ubuntu-latest
-            target: aarch64-unknown-linux-gnu
-          - os: ubuntu-latest
-            target: i686-unknown-linux-gnu
-          - os: macos-latest
-            target: x86_64-apple-darwin
-          - os: windows-latest
-            target: x86_64-pc-windows-msvc
+  cd:
+    uses: gifnksm/rust-template/.github/workflows/reusable-cd.yml@main
+    with:
+      upload-dist-archive: true
+
+  cd-complete:
+    needs: cd
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
     steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: ${{ matrix.rust }}
-      - uses: Swatinem/rust-cache@v2
-        with:
-          key: ${{ matrix.job.target }}
-      - name: Install cross
-        uses: taiki-e/install-action@v2
-        with:
-          tool: cross
-
-      - name: cargo xtask dist
-        run: cargo xtask dist --use-cross-if-needed --target ${{ matrix.job.target }}
-        shell: bash
-
-      - name: Upload binaries as artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          path: target/dist/*
-
-      - name: Releasing assets
-        uses: softprops/action-gh-release@v1
-        with:
-          files: target/dist/*
-          generate_release_notes: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        if: ${{ startsWith(github.ref, 'refs/tags/') }}
+      - run: |
+          if ${{ needs.cd.result == 'success' }}; then
+            echo "CD succeeded"
+            exit 0
+          else
+            echo "CD failed"
+            exit 1
+          fi
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,137 +10,19 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  set-matrix:
+  ci:
+    uses: gifnksm/rust-template/.github/workflows/reusable-ci.yml@main
+
+  ci-complete:
+    needs: ci
     runs-on: ubuntu-latest
-    outputs:
-      rust: ${{ steps.set-values.outputs.rust }}
-      os: ${{ steps.set-values.outputs.os }}
+    if: ${{ always() }}
     steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - name: Set matrix values
-        id: set-values
-        run: |
-          root_package_id="$(cargo metadata --format-version 1 | jq -cr '.resolve.root')"
-          root_package="$(cargo metadata --format-version 1 | jq -c --arg pkgid "${root_package_id}" '.packages[] | select(.id == $pkgid)')"
-          echo "${root_package}" | jq -c '{ root_package: .name }'
-
-          msrv="$(echo "${root_package}" | jq '.rust_version')"
-          rust="$(echo "[\"stable\", ${msrv}]" | jq -c)"
-          echo "rust=${rust}" >> "$GITHUB_OUTPUT"
-
-          os="$(echo '["ubuntu-latest", "macos-latest", "windows-latest"]' | jq -c)"
-          echo "os=${os}" >> "$GITHUB_OUTPUT"
-
-          jq -n --argjson rust "${rust}" --argjson os "${os}" '{ rust: $rust, os: $os }'
-
-  test:
-    name: Test
-    needs: set-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        rust: ${{ fromJSON(needs.set-matrix.outputs.rust) }}
-        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: ${{ matrix.rust }}
-      - uses: Swatinem/rust-cache@v2
-      - run: cargo xtask test --exhaustive
-        shell: bash
-
-  coverage:
-    name: Coverage (test)
-    needs: set-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        rust: [ stable ]
-        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: ${{ matrix.rust }}
-          components: llvm-tools-preview
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-llvm-cov
-      - run: cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
-        shell: bash
-      - uses: codecov/codecov-action@v3
-        with:
-          files: lcov.info
-          fail_ci_if_error: true
-
-  build:
-    name: Build
-    needs: set-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        rust: ${{ fromJSON(needs.set-matrix.outputs.rust) }}
-        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: ${{ matrix.rust }}
-      - uses: Swatinem/rust-cache@v2
-      - run: cargo xtask build --exhaustive -- --all-targets
-        shell: bash
-
-  lint:
-    name: Lint
-    needs: set-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        os: ${{ fromJSON(needs.set-matrix.outputs.os) }}
-    runs-on: ${{ matrix.os }}
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@stable
-        with:
-          components: rustfmt,clippy
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-udeps
-      - run: rustup toolchain add nightly --profile minimal
-        shell: bash
-      - run: cargo xtask lint --exhaustive
-        shell: bash
-
-  release-dry-run:
-    name: Release dry run
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-udeps,cargo-release
-      - run: rustup toolchain add nightly --profile minimal
-        shell: bash
-      - run: cargo release patch -vv --allow-branch '*'
-        shell: bash
-
-  actionlint:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Check workflow files
-        run: |
-          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
-          echo "::add-matcher::.github/actionlint-matcher.json"
-          ./actionlint -color
-        shell: bash
+      - run: |
+          if ${{ needs.ci.result == 'success' }}; then
+            echo "CI succeeded"
+            exit 0
+          else
+            echo "CI failed"
+            exit 1
+          fi
